apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  database_url: "postgres://myuser:YOUR_POSTGRES_PASSWORD@postgres:5432/mydatabase"
  rabbitmq_url: "amqp://myuser:YOUR_RABBITMQ_PASSWORD@rabbitmq:5672/"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: YOUR_POSTGRES_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  password: YOUR_RABBITMQ_PASSWORD
